name: Build projects manifest (with watermark)
permissions:
  contents: write

on:
  push:
    paths:
      - 'images/**'
      - 'assets/**'
      - '.github/workflows/build-projects.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # ImageMagick + SVG 변환기 설치
      - name: Install ImageMagick (and SVG support)
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick librsvg2-bin

      - name: Generate watermarked images + projects.json
        shell: bash
        run: |
          set -euo pipefail
          shopt -s nullglob

          OUT_BASE="wm_images"
          mkdir -p "$OUT_BASE"

          # 워터마크 파일 결정 (SVG면 PNG로 1회 변환)
          if [ -f assets/watermark.png ]; then
            WM_SRC="assets/watermark.png"
          elif [ -f assets/watermark.svg ]; then
            rsvg-convert -w 1200 assets/watermark.svg -o /tmp/wm.png
            WM_SRC="/tmp/wm.png"
          else
            echo "::warning::No watermark found (assets/watermark.svg or .png). Proceeding without watermark."
            WM_SRC=""
          fi
          echo "Using watermark: ${WM_SRC:-none}"

          # 합성 파라미터
          WM_PCT=18      # 입력 이미지 가로의 18%
          WM_OPACITY=30  # 30% 불투명도

          echo "[" > projects.json
          first_proj=1

          for dir in images/*/ ; do
            [ -d "$dir" ] || continue
            id=$(basename "$dir")
            mkdir -p "$OUT_BASE/$id"

            # 대표 이미지 탐색
            cover=""
            for c in "$dir"cover.*; do [ -f "$c" ] && cover=$(basename "$c") && break; done
            if [ -z "$cover" ]; then
              for f in "$dir"*.*; do
                case "${f##*.}" in jpg|jpeg|png|webp|gif|JPG|JPEG|PNG|WEBP|GIF) cover=$(basename "$f"); break;; esac
              done
            fi

            imgs=""
            first=1

            # 이미지들 처리
            while IFS= read -r -d '' f; do
              base=$(basename "$f")

              if [ -n "$WM_SRC" ]; then
                # 입력 폭 측정 → 워터마크 폭 계산(퍼센트)
                W=$(identify -format "%w" "$f")
                WM_W=$(( W * WM_PCT / 100 ))
                # 단일 괄호로 오버레이 + 투명도
                magick "$f" \
                  \( "$WM_SRC" -resize "${WM_W}x" -alpha on -channel A -evaluate set ${WM_OPACITY}% \) \
                  -gravity southeast -compose over -geometry +24+24 -composite \
                  "$OUT_BASE/$id/$base"
              else
                cp "$f" "$OUT_BASE/$id/$base"
              fi

              if [ $first -eq 1 ]; then imgs="\"$base\""; first=0; else imgs="$imgs, \"$base\""; fi
            done < <(find "$dir" -maxdepth 1 -type f -iregex '.*\.\(jpg\|jpeg\|png\|webp\|gif\)$' -print0 | sort -z)

            [ -z "$imgs" ] && continue

            # meta.txt → title/desc
            title=""; desc=""
            if [ -f "${dir}meta.txt" ]; then
              title=$(grep -i '^title:' "${dir}meta.txt" | sed 's/^title:[[:space:]]*//; s/\r//g; s/\n/ /g; s/\\/\\\\/g; s/"/\\"/g')
              desc=$(grep -i '^desc:'  "${dir}meta.txt" | sed  's/^desc:[[:space:]]*//;  s/\r//g; s/\n/ /g; s/\\/\\\\/g; s/"/\\"/g')
            fi

            # JSON 레코드
            if [ $first_proj -eq 0 ]; then echo "," >> projects.json; fi
            echo -n "  {\"id\":\"$id\",\"title\":\"${title:-$id}\",\"desc\":\"$desc\",\"cover\":\"$cover\",\"images\":[${imgs}]}" >> projects.json
            first_proj=0
          done
          echo -e "\n]" >> projects.json

      - name: Commit manifest and watermarked images
        uses: EndBug/add-and-commit@v9
        with:
          add: 'projects.json wm_images'
          message: 'Auto: watermark & projects.json'
