name: Build projects manifest
on:
  push:
    paths:
      - 'images/**'
      - '.github/workflows/build-projects.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate projects.json
        shell: bash
        run: |
          set -e
          echo "[" > projects.json
          first_proj=1
          for dir in images/*/ ; do
            [ -d "$dir" ] || continue
            id=$(basename "$dir")

            # 대표이미지 선택
            cover=""
            for c in "$dir"cover.*; do [ -f "$c" ] && cover=$(basename "$c") && break; done
            if [ -z "$cover" ]; then
              for f in "$dir"*.*; do
                case "${f##*.}" in jpg|jpeg|png|webp|gif|JPG|JPEG|PNG|WEBP|GIF) cover=$(basename "$f"); break;; esac
              done
            fi

            # 이미지 목록
            imgs=""
            first=1
            for f in "$dir"*.*; do
              case "${f##*.}" in jpg|jpeg|png|webp|gif|JPG|JPEG|PNG|WEBP|GIF)
                name=$(basename "$f")
                if [ $first -eq 1 ]; then imgs="\"$name\""; first=0; else imgs="$imgs, \"$name\""; fi
              ;;
              esac
            done
            [ -z "$imgs" ] && continue

            # 메타 읽기(옵션)
            title=""
            desc=""
            if [ -f "${dir}title.txt" ]; then
              title=$(sed ':a;N;$!ba;s/\r//g;s/"/\\"/g;s/\n/ /g' "${dir}title.txt")
            fi
            if [ -f "${dir}desc.txt" ]; then
              desc=$(sed ':a;N;$!ba;s/\r//g;s/"/\\"/g;s/\n/ /g' "${dir}desc.txt")
            fi

            # JSON 출력
            if [ $first_proj -eq 0 ]; then echo "," >> projects.json; fi
            echo -n "  {\"id\":\"$id\",\"title\":\"${title:-$id}\",\"desc\":\"$desc\",\"cover\":\"$cover\",\"images\":[${imgs}]}" >> projects.json
            first_proj=0
          done
          echo -e "\n]" >> projects.json

      - name: Commit manifest
        uses: EndBug/add-and-commit@v9
        with:
          add: 'projects.json'
          message: 'Auto-generate projects.json (with titles/descs)'
