name: Build projects manifest (with watermark)
permissions:
  contents: write

on:
  push:
    paths:
      - 'images/**'
      - 'assets/**'
      - '.github/workflows/build-projects.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate watermarked images + projects.json
        shell: bash
        run: |
          set -euo pipefail
          shopt -s nullglob

          OUT_BASE="wm_images"
          mkdir -p "$OUT_BASE"

          # 워터마크 소스 결정
          if [ -f assets/watermark.svg ]; then
            WM_SRC="assets/watermark.svg"
          elif [ -f assets/watermark.png ]; then
            WM_SRC="assets/watermark.png"
          else
            echo "No watermark asset found in assets/. Create assets/watermark.svg" >&2
            WM_SRC=""
          fi

          # magick/convert 중 가능한 명령 사용
          MAGICK=$(command -v magick || true)
          CONVERT=$(command -v convert || true)
          if [ -n "$MAGICK" ]; then
            run_wm () { magick "$@"; }
          elif [ -n "$CONVERT" ]; then
            run_wm () { convert "$@"; }
          else
            echo "ImageMagick not found on runner" >&2
            exit 1
          fi

          echo "[" > projects.json
          first_proj=1

          for dir in images/*/ ; do
            [ -d "$dir" ] || continue
            id=$(basename "$dir")
            mkdir -p "$OUT_BASE/$id"

            # 대표 찾기
            cover=""
            for c in "$dir"cover.*; do [ -f "$c" ] && cover=$(basename "$c") && break; done
            if [ -z "$cover" ]; then
              for f in "$dir"*.*; do
                case "${f##*.}" in jpg|jpeg|png|webp|gif|JPG|JPEG|PNG|WEBP|GIF) cover=$(basename "$f"); break;; esac
              done
            fi

            # 이미지 목록 + 워터마크 생성
            imgs=""
            first=1
            while IFS= read -r -d '' f; do
              base=$(basename "$f")
              ext="${base##*.}"
              # 워터마크 적용(오른쪽 아래, 30% 불투명, 크기 = 원본 가로의 약 18%)
              if [ -n "$WM_SRC" ]; then
                run_wm "$f" \( "$WM_SRC" -resize 18% -alpha set -channel A -evaluate set 30% \) \
                  -gravity southeast -geometry +24+24 -composite "$OUT_BASE/$id/$base"
              else
                # 워터마크 파일이 없으면 그냥 복사
                cp "$f" "$OUT_BASE/$id/$base"
              fi

              if [ $first -eq 1 ]; then imgs="\"$base\""; first=0; else imgs="$imgs, \"$base\""; fi
            done < <(find "$dir" -maxdepth 1 -type f -iregex '.*\.\(jpg\|jpeg\|png\|webp\|gif\)$' -print0 | sort -z)

            [ -z "$imgs" ] && continue

            # meta.txt
            title=""
            desc=""
            if [ -f "${dir}meta.txt" ]; then
              title=$(grep -i '^title:' "${dir}meta.txt" | sed 's/^title:[[:space:]]*//; s/\r//g; s/\n/ /g; s/\\/\\\\/g; s/"/\\"/g')
              desc=$(grep -i '^desc:'  "${dir}meta.txt" | sed 's/^desc:[[:space:]]*//;  s/\r//g; s/\n/ /g; s/\\/\\\\/g; s/"/\\"/g')
            fi

            # JSON 출력
            if [ $first_proj -eq 0 ]; then echo "," >> projects.json; fi
            echo -n "  {\"id\":\"$id\",\"title\":\"${title:-$id}\",\"desc\":\"$desc\",\"cover\":\"$cover\",\"images\":[${imgs}]}" >> projects.json
            first_proj=0
          done
          echo -e "\n]" >> projects.json

      - name: Commit manifest and watermarked images
        uses: EndBug/add-and-commit@v9
        with:
          add: 'projects.json wm_images'
          message: 'Auto: watermark & projects.json'
